// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCwbpgfmhbsiqUwytNf8HQY08R7IVX_Xs',
    appId: '1:346131389121:web:6e26c19c153d3396bd5240',
    messagingSenderId: '346131389121',
    projectId: 'rope-17617',
    authDomain: 'rope-17617.firebaseapp.com',
    storageBucket: 'rope-17617.appspot.com',
    measurementId: 'G-6CVZ6K5M4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWCbP2k60dUOehJjS0uhjjJhSkNqVpq8',
    appId: '1:346131389121:android:a4abbab9d36f56b9bd5240',
    messagingSenderId: '346131389121',
    projectId: 'rope-17617',
    storageBucket: 'rope-17617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY_Sl6fW6nubwVZ5-Gp_F9xQePp9_Vsvs',
    appId: '1:346131389121:ios:320ec35be1968873bd5240',
    messagingSenderId: '346131389121',
    projectId: 'rope-17617',
    storageBucket: 'rope-17617.appspot.com',
    iosClientId: '346131389121-o2cfi4rinaa2g1pj1ro19d0jujic230i.apps.googleusercontent.com',
    iosBundleId: 'com.example.rope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY_Sl6fW6nubwVZ5-Gp_F9xQePp9_Vsvs',
    appId: '1:346131389121:ios:320ec35be1968873bd5240',
    messagingSenderId: '346131389121',
    projectId: 'rope-17617',
    storageBucket: 'rope-17617.appspot.com',
    iosClientId: '346131389121-o2cfi4rinaa2g1pj1ro19d0jujic230i.apps.googleusercontent.com',
    iosBundleId: 'com.example.rope',
  );
}
